version: '3'
services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/nginx-logs:/app/nginx/logs
      - ./volumes/nginx-conf:/etc/nginx:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /www:/www:ro
      - /root/work/dhparam:/root/work/dhparam:ro

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - /usr/lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./volumes/jenkins-data:/var/jenkins_home:rw
    extra_hosts:
      - "repo.eulerproject.io:172.17.0.1"

  nexus:
    image: sonatype/nexus3
    volumes:
      - ./volumes/nexus-data:/nexus-data

